name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: 🚀 Deploy to Hostinger
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        port: ${{ secrets.HOSTINGER_PORT }}
        script: |
          # Navigate to website directory
          cd ${{ secrets.DEPLOY_PATH }}
          
          # Preserve files that shouldn't be overwritten
          echo "💾 Preserving configuration files..."
          PRESERVE_FILES=".htaccess"
          TEMP_DIR=$(mktemp -d)
          
          for file in $PRESERVE_FILES; do
            if [ -f "$file" ]; then
              cp "$file" "$TEMP_DIR/"
              echo "✅ Preserved $file"
            fi
          done
          
          # Force update from git
          echo "📥 Updating from repository..."
          git fetch origin main
          git reset --hard origin/main
          
          # Restore preserved files
          echo "🔄 Restoring configuration files..."
          for file in $PRESERVE_FILES; do
            if [ -f "$TEMP_DIR/$file" ]; then
              cp "$TEMP_DIR/$file" ./
              echo "✅ Restored $file"
            fi
          done
          
          # Clean up
          rm -rf "$TEMP_DIR"
          
          # Create constant.php from template if it doesn't exist
          if [ ! -f "constant.php" ] && [ -f "constant.php.example" ]; then
            echo "⚠️  constant.php not found! Please create it from constant.php.example"
            echo "Creating constant.php with environment variables..."
            cp constant.php.example constant.php
            
            # Replace with actual values from GitHub secrets
            sed -i "s/'localhost'/'127.0.0.1'/g" constant.php
            sed -i "s/'your_database_name'/'${{ secrets.DB_NAME }}'/g" constant.php
            sed -i "s/'your_database_user'/'${{ secrets.DB_USER }}'/g" constant.php
            sed -i "s/'your_database_password'/'${{ secrets.DB_PASSWORD }}'/g" constant.php
          fi
          
          # Set correct permissions
          echo "🔧 Setting permissions..."
          find . -type d -not -path "./.git/*" -exec chmod 755 {} \;
          find . -type f -not -path "./.git/*" -exec chmod 644 {} \;
          
          # Show deployment info
          echo "📊 Deployment Summary:"
          echo "- Current commit: $(git rev-parse --short HEAD)"
          echo "- Branch: $(git branch --show-current)"
          echo "- constant.php exists: $([ -f constant.php ] && echo 'YES' || echo 'NO')"
          
          echo "✅ Deployment completed successfully!"